spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.0.66:28080/auth/realms/marketplace
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.66:28080/realms/master