spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: https://nabagagem-keycloak.herokuapp.com/auth/realms/nabagagem
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: https://nabagagem-keycloak.herokuapp.com/auth/realms/nabagagem
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: market
    password: place